postsubmits:
  falcosecurity/test-infra:
    - name: sync-ghrepos-secrets-vars-post-submit
      branches:
        - ^master$
      decorate: true
      max_concurrency: 1
      skip_report: false
      run_if_changed: '^config/pigeon.yaml$|^config/jobs/pigeon/.*'
      spec:
        containers:
          - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/pigeon:latest
            command:
              - pigeon
            args:
              - -gh-token /etc/github-token/oauth
              - -conf config/pigeon.yaml
            volumeMounts:
              - name: github
                mountPath: /etc/github-token
        volumes:
          - name: github
            secret:
              secretName: oauth-token
        nodeSelector:
          Archtype: "x86"
