periodics:
  - cron: "05 15 * * 1"  # Run at 15:05 PST (15:05 UTC) Mon
    name: ci-test-infra-autobump-prow-for-auto-deploy
    decorate: true
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    spec:
      containers:
      - image: gcr.io/k8s-prow/generic-autobumper:latest
        command:
        - generic-autobumper
        args:
        - --config=config/prow/autobump-config.yaml
        - --labels-override=skip-review # This label is used by tide for identifying trusted PR
        - --skip-if-no-oncall # Only apply `skip-review` label when oncall is active
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: ssh
          mountPath: /root/.ssh
      volumes:
      - name: github
        secret:
          secretName: oauth-token
      - name: ssh
        secret:
          secretName: poiana-ssh-keys
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
    annotations:
      description: runs autobumper to create/update a PR that bumps prow to the latest RC with label 'skip-review'

postsubmits:
  falcosecurity/test-infra:
  - name: post-test-infra-deploy-prow
    run_if_changed: '^(config/prow/)'
    decorate: true
    branches:
    - ^master$
    max_concurrency: 1
    spec:
      serviceAccountName: deployer
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
        command:
        - make
        args:
        - -C
        - config/prow
        - deploy-all
      annotations:
        description: deploys the configured version of prow by running prow/deploy.sh
    nodeSelector:
      Archtype: "x86"
